/* eslint-disable */
/* AUTO-GENERATED by scripts/gen-api-types.py — do not edit. */

export interface ActionLogOut {
  id: number;
  action_type: string;
  summary: string;
  created_at: string;
  undone_at: string | null;
  undoable: boolean;
  actor_user_id: number | null;
}

export interface ChangePasswordIn {
  password: string;
}

export interface CreateUserIn {
  email: string;
  password: string;
  role?: "admin" | "warehouse" | "finance" | "customer";
  display_name?: string;
}

export interface DepositConfirmIn {
  payment_ref?: string;
}

export interface FinanceMonthBucket {
  goods_jpy: number;
  shipping_jpy: number;
  total_jpy: number;
  goods_cny: number | null;
  shipping_cny: number | null;
  total_cny: number | null;
  order_count: number;
  missing_rate_count: number;
}

export interface FinanceOutboundBucket {
  goods_jpy: number;
  goods_receivable_cny: number | null;
  freight_cny: number | null;
  amount_receivable_cny: number | null;
  amount_received_cny: number;
  amount_unreceived_cny: number | null;
  batch_count: number;
}

export interface FinanceSummaryOut {
  month: string;
  ordered: FinanceMonthBucket;
  outbound: FinanceOutboundBucket;
}

export interface HTTPValidationError {
  detail: Array<ValidationError>;
}

export interface InboundCreate {
  tracking_no?: string;
  carrier?: "yamato" | "sagawa" | "other";
  item_ids: Array<number>;
}

export interface ItemBatchCreate {
  items: Array<ItemCreate>;
}

export interface ItemCreate {
  name: string;
  shop?: string;
  order_ref?: string;
  qty?: number;
  unit_cost?: number | null;
  note?: string;
  animegood_product_id?: number | null;
  ip?: string;
  product_kind?: string;
  image_url?: string;
  source_url?: string;
  expected_ship_at?: string | null;
  expected_ship_period?: "early" | "mid" | "late" | null;
  barcode?: string;
  order_qty?: number | null;
  order_image_url?: string;
}

export interface ItemOut {
  id: number;
  order_id: number;
  name: string;
  shop: string;
  order_ref: string;
  qty: number;
  unit_cost: number | null;
  status: "ordered" | "inbound_shipped" | "in_stock" | "outbound_shipped" | "delivered" | "cancelled";
  ordered_at: string;
  arrived_at: string | null;
  expected_ship_at: string | null;
  expected_ship_period: "early" | "mid" | "late" | null;
  barcode: string;
  note: string;
  animegood_product_id: number | null;
  ip: string;
  product_kind: string;
  image_url: string;
  source_url: string;
  inbound_tracking_no: string | null;
  inbound_carrier: "yamato" | "sagawa" | "other" | null;
  inbound_tracking_url: string | null;
  inbound_shipment_id: number | null;
  outbound_tracking_no: string | null;
  outbound_carrier: "yamato" | "sagawa" | "other" | null;
  outbound_tracking_url: string | null;
  outbound_shipment_id: number | null;
  outbound_box_no: number | null;
  order_qty: number | null;
  order_image_url: string;
}

export interface ItemUpdate {
  name?: string | null;
  shop?: string | null;
  order_ref?: string | null;
  qty?: number | null;
  unit_cost?: number | null;
  note?: string | null;
  status?: "ordered" | "inbound_shipped" | "in_stock" | "outbound_shipped" | "delivered" | "cancelled" | null;
  animegood_product_id?: number | null;
  ip?: string | null;
  product_kind?: string | null;
  image_url?: string | null;
  source_url?: string | null;
  expected_ship_at?: string | null;
  expected_ship_period?: "early" | "mid" | "late" | null;
  barcode?: string | null;
}

export interface LineCreate {
  name: string;
  shop?: string;
  qty?: number;
  unit_cost?: number | null;
  note?: string;
  animegood_product_id?: number | null;
  ip?: string;
  product_kind?: string;
  image_url?: string;
  source_url?: string;
  expected_ship_at?: string | null;
  expected_ship_period?: "early" | "mid" | "late" | null;
  barcode?: string;
}

export interface LineOut {
  id: number;
  order_id: number;
  name: string;
  shop: string;
  order_ref: string;
  qty: number;
  unit_cost: number | null;
  status: "ordered" | "inbound_shipped" | "in_stock" | "outbound_shipped" | "delivered" | "cancelled";
  ordered_at: string;
  arrived_at: string | null;
  expected_ship_at: string | null;
  expected_ship_period: "early" | "mid" | "late" | null;
  barcode: string;
  note: string;
  animegood_product_id: number | null;
  ip: string;
  product_kind: string;
  image_url: string;
  source_url: string;
  inbound_tracking_no: string | null;
  inbound_carrier: "yamato" | "sagawa" | "other" | null;
  inbound_tracking_url: string | null;
  inbound_shipment_id: number | null;
  outbound_tracking_no: string | null;
  outbound_carrier: "yamato" | "sagawa" | "other" | null;
  outbound_tracking_url: string | null;
  outbound_shipment_id: number | null;
  outbound_box_no: number | null;
}

export interface LoginIn {
  email: string;
  password: string;
}

export interface OrderCreate {
  order_ref?: string;
  shop?: string;
  order_qty?: number | null;
  shipping_fee?: number | null;
  exchange_rate?: number | null;
  order_image_url?: string;
  note?: string;
  expected_ship_at?: string | null;
  expected_ship_period?: "early" | "mid" | "late" | null;
  lines: Array<LineCreate>;
}

export interface OrderGroupOut {
  order_id: number | null;
  order_ref: string;
  items: Array<ShipmentItemOut>;
}

export interface OrderOut {
  id: number;
  order_ref: string;
  shop: string;
  status: "ordered" | "inbound_shipped" | "in_stock" | "outbound_shipped" | "delivered" | "cancelled";
  ordered_at: string;
  order_qty: number | null;
  shipping_fee: number | null;
  exchange_rate: number | null;
  order_image_url: string;
  note: string;
  expected_ship_at: string | null;
  expected_ship_period: "early" | "mid" | "late" | null;
  line_count: number;
  total_qty: number;
  goods_total: number | null;
  order_total: number | null;
  goods_total_cny: number | null;
  shipping_fee_cny: number | null;
  order_total_cny: number | null;
  lines: Array<LineOut>;
}

export interface OrderRequestConfirm {
  shop_order_ref: string;
  staff_note?: string;
  create_stock_order?: boolean;
  shipping_fee?: number | null;
  exchange_rate?: number | null;
}

export interface OrderRequestCreate {
  name: string;
  shop?: string;
  unit_cost?: number | null;
  image_url?: string;
  source_url: string;
  ip?: string;
  barcode?: string;
  qty?: number;
  contact?: string;
  note?: string;
}

export interface OrderRequestOut {
  id: number;
  request_code: string;
  account_order_no: string;
  status: "pending_payment" | "submitted" | "ordered" | "rejected";
  name: string;
  shop: string;
  unit_cost: number | null;
  image_url: string;
  source_url: string;
  ip: string;
  barcode: string;
  qty: number;
  contact: string;
  note: string;
  shop_order_ref: string;
  ordered_at: string | null;
  staff_note: string;
  reject_reason: string;
  stock_order_id: number | null;
  user_id: number | null;
  deposit_rate: number | null;
  deposit_amount: number | null;
  deposit_paid_at: string | null;
  payment_ref: string;
  created_at: string;
  updated_at: string;
}

export interface OrderRequestPublicOut {
  request_code: string;
  account_order_no: string;
  status: "pending_payment" | "submitted" | "ordered" | "rejected";
  name: string;
  shop: string;
  unit_cost: number | null;
  amount: number | null;
  image_url: string;
  source_url: string;
  qty: number;
  shop_order_ref: string;
  ordered_at: string | null;
  staff_note: string;
  reject_reason: string;
  created_at: string;
  updated_at: string;
  status_label: string;
  deposit_rate: number | null;
  deposit_amount: number | null;
  deposit_paid_at: string | null;
  payment_ref: string;
}

export interface OrderRequestReject {
  reject_reason: string;
}

export interface OrderUpdate {
  order_ref?: string | null;
  shop?: string | null;
  order_qty?: number | null;
  shipping_fee?: number | null;
  exchange_rate?: number | null;
  order_image_url?: string | null;
  note?: string | null;
  expected_ship_at?: string | null;
  expected_ship_period?: "early" | "mid" | "late" | null;
  status?: "ordered" | "inbound_shipped" | "in_stock" | "outbound_shipped" | "delivered" | "cancelled" | null;
}

export interface OutboundBatchCreate {
  note?: string;
  boxes: Array<OutboundBoxCreate>;
  allow_missing_barcode?: boolean;
  missing_barcode_note?: string;
  freight_exchange_rate?: number | null;
  freight_unit_price_jpy?: number | null;
  chargeable_weight?: number | null;
  invoice_ship_date?: string | null;
}

export interface OutboundBatchFinanceUpdate {
  freight_exchange_rate?: number | null;
  freight_unit_price_jpy?: number | null;
  chargeable_weight?: number | null;
  amount_received_cny?: number | null;
  payment_note?: string | null;
  invoice_ship_date?: string | null;
}

export interface OutboundBatchOut {
  id: number;
  note: string;
  created_at: string;
  boxes: Array<OutboundBoxOut>;
  box_count: number;
  item_count: number;
  goods_jpy: number | null;
  order_shipping_jpy: number | null;
  goods_receivable_cny: number | null;
  freight_exchange_rate: number | null;
  freight_unit_price_jpy: number | null;
  chargeable_weight: number | null;
  freight_cny: number | null;
  amount_receivable_cny: number | null;
  amount_received_cny: number;
  amount_unreceived_cny: number | null;
  payment_status: "unpaid" | "partial" | "paid";
  payment_note: string;
  invoice_ship_date: string | null;
}

export interface OutboundBatchUpdate {
  note?: string | null;
  boxes: Array<OutboundBoxUpdate>;
  allow_missing_barcode?: boolean;
  missing_barcode_note?: string;
  invoice_ship_date?: string | null;
}

export interface OutboundBoxCreate {
  box_no?: number | null;
  carrier?: "yamato" | "sagawa" | "other";
  tracking_no: string;
  note?: string;
  item_ids: Array<number>;
  net_weight?: number | null;
  gross_weight?: number | null;
  length_cm?: number | null;
  width_cm?: number | null;
  height_cm?: number | null;
}

export interface OutboundBoxItemUpdate {
  item_id: number;
  qty?: number | null;
}

export interface OutboundBoxOut {
  id: number;
  batch_id: number;
  box_no: number;
  carrier: "yamato" | "sagawa" | "other";
  tracking_no: string;
  tracking_url: string | null;
  status: "shipped" | "delivered";
  shipped_at: string;
  delivered_at: string | null;
  note: string;
  net_weight: number | null;
  gross_weight: number | null;
  length_cm: number | null;
  width_cm: number | null;
  height_cm: number | null;
  items: Array<ShipmentItemOut>;
  order_groups: Array<OrderGroupOut>;
}

export interface OutboundBoxUpdate {
  box_no: number;
  carrier?: "yamato" | "sagawa" | "other";
  tracking_no: string;
  note?: string;
  items: Array<OutboundBoxItemUpdate>;
  net_weight?: number | null;
  gross_weight?: number | null;
  length_cm?: number | null;
  width_cm?: number | null;
  height_cm?: number | null;
}

export interface OutboundInvPreview {
  note?: string;
  boxes: Array<OutboundBoxCreate>;
  freight_exchange_rate?: number | null;
  freight_unit_price_jpy?: number | null;
  chargeable_weight?: number | null;
  invoice_ship_date?: string | null;
}

export interface RegisterCustomerIn {
  email: string;
  password: string;
  display_name?: string;
}

export interface ScrapeProduct {
  name: string;
  shop: string;
  unit_cost: number | null;
  image_url: string;
  source_url: string;
  ip: string;
  barcode: string;
  qty: number | null;
  expected_ship_at: string | null;
  expected_ship_period: "early" | "mid" | "late" | null;
  release_date: string | null;
}

export interface ScrapeRequest {
  url?: string;
  html?: string | null;
}

export interface ScrapeResult {
  kind: string;
  products: Array<ScrapeProduct>;
  message: string;
  order_ref: string;
  shipping_fee: number | null;
  order_total: number | null;
}

export interface SetActiveIn {
  is_active: boolean;
}

export interface ShipmentCreate {
  tracking_no?: string;
  direction?: "inbound" | "outbound";
  carrier?: "yamato" | "sagawa" | "other";
  item_ids: Array<number>;
  order_id?: number | null;
}

export interface ShipmentItemOut {
  id: number;
  order_id: number | null;
  order_ref: string;
  name: string;
  shop: string;
  qty: number;
  status: "ordered" | "inbound_shipped" | "in_stock" | "outbound_shipped" | "delivered" | "cancelled";
  barcode: string;
}

export interface ShipmentOut {
  id: number;
  direction: "inbound" | "outbound";
  carrier: "yamato" | "sagawa" | "other";
  tracking_no: string;
  tracking_url: string | null;
  shipped_at: string;
  delivered_at: string | null;
  status: "shipped" | "delivered";
  order_id: number | null;
  batch_id: number | null;
  box_no: number | null;
  items: Array<ShipmentItemOut>;
  order_groups: Array<OrderGroupOut>;
}

export interface StatsOut {
  ordered: number;
  inbound_shipped: number;
  in_stock: number;
  outbound_shipped: number;
  delivered: number;
  cancelled: number;
  inbound_shipments_shipped: number;
  outbound_shipments_shipped: number;
  shipments_delivered: number;
  orders_total: number;
}

export interface StockBoxChildOut {
  id: number;
  box_no: number;
  note: string;
  order_count: number;
  item_count: number;
}

export interface StockBoxCreate {
  order_ids: Array<number>;
  note?: string;
  box_no?: number | null;
}

export interface StockBoxLineOut {
  id: number;
  order_id: number;
  name: string;
  shop: string;
  order_ref: string;
  qty: number;
  status: "ordered" | "inbound_shipped" | "in_stock" | "outbound_shipped" | "delivered" | "cancelled";
  image_url: string;
  barcode: string;
  ip: string;
  product_kind: string;
  note: string;
  source_url: string;
}

export interface StockBoxMergeChild {
  child_box_id: number;
}

export interface StockBoxOrderOut {
  id: number;
  order_ref: string;
  shop: string;
  status: "ordered" | "inbound_shipped" | "in_stock" | "outbound_shipped" | "delivered" | "cancelled";
  line_count: number;
  total_qty: number;
  lines: Array<StockBoxLineOut>;
}

export interface StockBoxOrdersPayload {
  order_ids: Array<number>;
}

export interface StockBoxOut {
  id: number;
  box_no: number;
  note: string;
  created_at: string;
  parent_id: number | null;
  parent_box_no: number | null;
  child_boxes: Array<StockBoxChildOut>;
  order_ids: Array<number>;
  order_count: number;
  item_count: number;
  orders: Array<StockBoxOrderOut>;
}

export interface StockBoxUpdate {
  note?: string | null;
  box_no?: number | null;
}

export interface UserOut {
  id: number;
  email: string;
  display_name: string;
  role: "admin" | "warehouse" | "finance" | "customer";
  is_active: boolean;
  created_at: string;
}

export interface ValidationError {
  loc: Array<string | number>;
  msg: string;
  type: string;
  input: unknown;
  ctx: Record<string, unknown>;
}
