from __future__ import annotations

"""Generate frontend/src/api-types.generated.ts from FastAPI OpenAPI schemas.

Run from stockgood/:

    python scripts/gen-api-types.py

No extra npm packages. Hand-written fetch wrappers stay in frontend/src/api.ts.
"""

import json
import sys
from pathlib import Path

STOCKGOOD_ROOT = Path(__file__).resolve().parent.parent
BACKEND_ROOT = STOCKGOOD_ROOT / "backend"
FRONTEND_TYPES = STOCKGOOD_ROOT / "frontend" / "src" / "api-types.generated.ts"

sys.path.insert(0, str(BACKEND_ROOT))

from app.main import app  # noqa: E402


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _ts_from_schema(schema: dict, schemas: dict, force_out_required: bool = False) -> str:
    if "$ref" in schema:
        return _ref_name(schema["$ref"])
    if "anyOf" in schema:
        parts = [_ts_from_schema(p, schemas, force_out_required) for p in schema["anyOf"]]
        if "null" in parts:
            others = [p for p in parts if p != "null"]
            inner = others[0] if len(others) == 1 else " | ".join(others)
            return f"{inner} | null"
        return " | ".join(parts)
    if "oneOf" in schema:
        return " | ".join(
            _ts_from_schema(p, schemas, force_out_required) for p in schema["oneOf"]
        )
    if "allOf" in schema:
        return " & ".join(
            _ts_from_schema(p, schemas, force_out_required) for p in schema["allOf"]
        )
    if "enum" in schema and "type" not in schema or (
        "enum" in schema and schema.get("type") == "string"
    ):
        if "enum" in schema and schema.get("type") in (None, "string"):
            return " | ".join(json.dumps(v, ensure_ascii=False) for v in schema["enum"])
    enum = schema.get("enum")
    typ = schema.get("type")
    if enum is not None and typ in (None, "string", "integer", "number"):
        return " | ".join(json.dumps(v, ensure_ascii=False) for v in enum)
    if typ == "string":
        return "string"
    if typ == "integer" or typ == "number":
        return "number"
    if typ == "boolean":
        return "boolean"
    if typ == "array":
        items = schema.get("items") or {}
        return f"Array<{_ts_from_schema(items, schemas, force_out_required)}>"
    if typ == "object" or "properties" in schema:
        return "Record<string, unknown>"
    if typ == "null":
        return "null"
    return "unknown"


def _treat_as_response(name: str) -> bool:
    if name.endswith(
        ("In", "Create", "Update", "Payload", "Preview", "Request", "Confirm", "Reject")
    ):
        return False
    return True


def _interface_body(name: str, schema: dict, schemas: dict) -> str:
    props = schema.get("properties") or {}
    required = set(schema.get("required") or [])
    treat_required = _treat_as_response(name)
    lines = [f"export interface {name} {{"]
    for key, prop in props.items():
        ts = _ts_from_schema(prop, schemas)
        optional = key not in required and not treat_required
        q = "?" if optional else ""
        lines.append(f"  {key}{q}: {ts};")
    lines.append("}")
    return "\n".join(lines)


def _type_alias(name: str, schema: dict, schemas: dict) -> str | None:
    if "enum" in schema and "properties" not in schema:
        union = " | ".join(json.dumps(v, ensure_ascii=False) for v in schema["enum"])
        return f"export type {name} = {union};"
    if schema.get("type") in ("string", "integer", "number", "boolean") and "enum" not in schema:
        return f"export type {name} = {_ts_from_schema(schema, schemas)};"
    if "$ref" in schema:
        return f"export type {name} = {_ref_name(schema['$ref'])};"
    if "anyOf" in schema or "oneOf" in schema or "allOf" in schema:
        return f"export type {name} = {_ts_from_schema(schema, schemas)};"
    return None


def generate() -> str:
    spec = app.openapi()
    schemas: dict = spec.get("components", {}).get("schemas", {})
    chunks = [
        "/* eslint-disable */",
        "/* AUTO-GENERATED by scripts/gen-api-types.py — do not edit. */",
        "",
    ]
    for name, schema in schemas.items():
        alias = _type_alias(name, schema, schemas)
        if alias:
            chunks.append(alias)
            chunks.append("")
            continue
        if schema.get("type") == "object" or "properties" in schema:
            chunks.append(_interface_body(name, schema, schemas))
            chunks.append("")
            continue
        chunks.append(f"export type {name} = {_ts_from_schema(schema, schemas)};")
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def main() -> None:
    text = generate()
    FRONTEND_TYPES.parent.mkdir(parents=True, exist_ok=True)
    FRONTEND_TYPES.write_text(text, encoding="utf-8")
    print(f"wrote {FRONTEND_TYPES.relative_to(STOCKGOOD_ROOT)}")


if __name__ == "__main__":
    main()
